### ISSUE TITLE
pages を components 以下に用意する

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#1]
`tomato_timer/src/pages/` に画面がありますが、これも
`tomato_timer/src/components/` に入れてしまったらどうか。

atomic design であれば、atoms とpages もあるので、コンポーネントとしてここにまとめてもよさそうに思います。
もちろん厳密にしないといけないわけではないので、好みでいいのですが。

見た目に関するものをcomponents 、内部の処理に関するもの、カスタムフック、データの型、などでまとめて置けるとわかりやすいですね。

**Comment by smallStall** [comment]
pagesなのですがNext.jsを使っている以上、src配下じゃないとうまくルーティングできないようです。

https://nextjs.org/docs/advanced-features/src-directory

**Comment by kakukakug** [comment]
たしかに、pagesのディレクトリは変更できなさそうですね。
atomic design のpages については一旦無視して、src 配下に置いたままにしておきましょう。
