### ISSUE TITLE
使わない引数は _event みたいにしておくとlint とかでわかりやすい

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#10]
https://github.com/smallStall/tomato_timer/blob/09e2a5699488170ad9a36a479914048a5ea72b0a/src/components/organisms/tomatoSlider.tsx#L72

ここの引数のevent は使わないのですが、1つ目の引数なので定義は省略できませんよね。
こういった場合に、よく「_」とか「_event」 という名前で定義するのがjsではよくみる形です。必要だから定義しているけど使わないよという意味です。

lint とかでもwarningが出ることがあるので覚えておくといいかも。
もちろん個人の好みによっても変わるので、取り入れても取り入れなくてもいいかなと思います。

**Comment by smallStall** [comment]
アンダースコアをつけると使わない変数ってことをlinterに教えられるんですね。
知りませんでした！これだとすごくわかりやすくなりますね。
