### ISSUE TITLE
STOPPED とか RUNNING の文字列はよく使うので定数オブジェクトとしても用意しておくのはどうか

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#11]
https://github.com/smallStall/tomato_timer/blob/09e2a5699488170ad9a36a479914048a5ea72b0a/src/types/intervalTimer.ts#L1

Status の型として、文字列のパターンを用意していますね。とても良いです！

ただ、実際にステータスを比較する時には
```
(status === "STOPPED" ? -- : -- )
```
みたいに、文字列を都度記述しています。
何度も出てくる文字列だと思いますので、型と合わせて実態のオブジェクトなんかを用意しておくといいかなと思います。

```
export const StatusValues: { [key: string]: Status } = {
  stopped: "STOPPED",
  running: "RUNNING",
  paused: "PAUSED",
  resume: "RESUME",
  finished: "FINISHED",
};
```
上記を用意しておけば、以下のようにかけますね。何度も出てくるものであればタイプミスとか減らす目的で、定数として用意しておくと良いです。
```
(status === StatusValues.stopped ? -- : -- )
```

その上でできれば status も`status:string` と文字列型になっている箇所があるので、できるなら`status:Status`と用意した型を使いたいですね。
もしも想定と異なる文字列が入ってしまう場合、ビルド時に発見できるようになるはず。

**Comment by smallStall** [comment]
statusを値オブジェクトにしました！
使ったことがほとんどなかったんですが、文字列がなくなってすっきりしますね！
