### ISSUE TITLE
styles を 各componentsと一緒においてしまってよさそう

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#2]
styles を components と分けた場所にまとめていますね。

Web では昔からこのような形が一般的なのですが、React 使ってコンポーネント単位で実装していくとなると、実際に利用されるコンポーネントのそばにあった方がわかりやすいことが多いと思います。
別々の場所にあってなんだか使いにくいいなあと感じたこととかないでしょうか？

たとえば

```
tomato_timer/src/components/organisms/footer.tsx 
tomato_timer/src/styles/components/footer.module.scss
```
を
```
tomato_timer/src/components/organisms/footer/index.tsx
tomato_timer/src/components/organisms/footer/styles.module.scss
```
にする。という形はよくありますね。
フッターに関連する見た目の実装がまとまるので、修正とかもしやすくなるかな。

もちろん共通化したいものとかもあると思うので、別の場所にある方がいい場合もあります。好みですかね。

**Comment by smallStall** [comment]
確かになんだか使いにくいような気がしていました！
styleフォルダまで遠いというか。
componentsに一緒に入れることにしました。
