### ISSUE TITLE
固定の数値は定数にしておくとわかりやすい

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#3]
https://github.com/smallStall/tomato_timer/blob/f47ed14e7e64008f412e17ce590464dcb044ca13/src/pages/index.tsx#L14-L15

特定の数値を使っていますが、ぱっと見では何の数値かわからなかったりします。
一度名前をつけた定数に入れておくことで、何の数値なのかわかりやすくなります。

さらに別の場所に移動させることで再利用もできますよね。いろんなところで使うようであれば共通化できるようにしておくと便利です。

間違いも減りますし、最大値を変更しようかなって時とかも一箇所直せば全部治るみたいな。

```
const MAX_WORK_COUNT = 25 * 60;
const MAX_REST_COUNT = 5 * 60;

const [maxWorkTime, setMaxWorkTime] = useState(MAX_WORK_COUNT);
const [maxRestTime, setMaxRestTime] = useState(MAX_REST_COUNT);
```

**Comment by smallStall** [comment]
定数に修正しました！
