### ISSUE TITLE
型をどこに配置するか

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#4]
https://github.com/smallStall/tomato_timer/blob/f47ed14e7e64008f412e17ce590464dcb044ca13/src/hooks/types.ts#L1

データの型を用意しているのはとても良いですね！

現在は`tomato_timer/src/hooks/types.ts` にまとめられていますが、これから増えていくようであれば
`tomato_timer/src/hooks/types/` ディレクトリを用意して、その中に目的や要素ごとに分けて定義するとよさそうです。

ほかにもコンポーネントでも参照するとかであれば`tomato_timer/src/hooks/` 以下でなく `tomato_timer/src/types/` に階層を上げるのも検討できますね。

**Comment by smallStall** [comment]
了解です。
コンポーネントでも参照するので、型情報をsrc/typesに移動しました。
