### ISSUE TITLE
reducer 関連のソースはまとめておいたらよさそう

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#5]
https://github.com/smallStall/tomato_timer/blob/f47ed14e7e64008f412e17ce590464dcb044ca13/src/hooks/reducer.ts#L1

https://github.com/smallStall/tomato_timer/blob/f47ed14e7e64008f412e17ce590464dcb044ca13/src/hooks/actions.ts#L1

現在、reducer 関連の`actions helper reducer `が hooks/ の中にありますが、他のカスタムフックと紛らわしいですね。
もっとたくさんカスタムフックが増える、またはreducer が増えるとごちゃごちゃになっていきそうです。

reducer 関連のディレクトリを用意してまとめておくとよさそうです。

**Comment by smallStall** [comment]
reducer関連をintervalTimerReducerのフォルダの中に入れました。
