### ISSUE TITLE
できれば let ではなく const を使いたい

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#6]
https://github.com/smallStall/tomato_timer/blob/f47ed14e7e64008f412e17ce590464dcb044ca13/src/components/organisms/themeIcon.tsx#L7-L17

変数の定義に let を使っていますが、特に必要なければconst を使うようにするといいです。

ざっくりとはlet は再代入可能で、上書き可能みたいなものです。
const は 基本的に再代入は不可能な書き方です。

一つ目のこれは、再代入しないのでconst でかけるはず。
```
    let currentTheme = localStorage.getItem("theme");
```

ふたつめは再代入して上書きしています。
```
    let   = document.documentElement.getAttribute("data-theme");
    currentTheme = currentTheme !== "light" ? "light" : "dark";
    setDarkMode(currentTheme);
```
ここではすぐ次の行でやっているので見落としませんが、離れた行で行うと見落としてしまったりして「思っていたものと違うものが入っていた」みたいなことになりやすいです。

なので同じ変数に再代入するのはなるべく避けたい。なのでなるべく const を使って実装できると安全です。

たとえばこうするとか。
```
    const currentTheme = document.documentElement.getAttribute("data-theme");
    const isDarkMode = currentTheme !== "light" ? "light" : "dark";
    setDarkMode(isDarkMode);
```

ちなみに以下の部分は currentTheme が light に一致しない場合 light、light に一致する場合 dark になりますが、意図的ですかね。ちょっと混乱しません？
 
`currentTheme !== "light" ? "light" : "dark";`

どうするのがいいだろうか？テーマの名前を逆にしてしまうとか、onLight / onDark とかにするとかですかね。

**Comment by smallStall** [comment]
1つ目のletをconstに修正しました。

data-theme, currentThemeの部分はisDarkと改称し、boolean型に変更しました。
ローカルストレージにboolean型を入れる際にはstringに変更されるので、JSON.parse()でbooleanに戻しました。

  useEffect(() => {
    const currentTheme = localStorage.getItem("isDark");
    if (currentTheme != null) {
      setDarkMode(JSON.parse(currentTheme));
      document.documentElement.setAttribute("isDark", currentTheme.toString());
    }
  }, []);

  const toggleDataTheme = () => {
    const currentTheme = document.documentElement.getAttribute("isDark");
    const newTheme: boolean = !JSON.parse(
      currentTheme == null ? "false" : currentTheme
    );
    setDarkMode(newTheme);
    document.documentElement.setAttribute("isDark", newTheme.toString());
    localStorage.setItem("isDark", newTheme.toString());
  };
