### ISSUE TITLE
state にしなくてもいいのかも

### ISSUE THREAD

**Issue by kakukakug** [smallStall/tomato_timer#9]
https://github.com/smallStall/tomato_timer/blob/09e2a5699488170ad9a36a479914048a5ea72b0a/src/pages/index.tsx#L18-L19

setMaxWorkTime
など使ってないようであれば、特にuseState する必要はないかもしれません。
将来的に、max を変更できるようなUIに拡張予定！とかであれば、このままがいいかも

**Comment by smallStall** [comment]
ここは他の時間も実装するかどうか悩んでいたところなのですが、
しばらくは実装しなさそうなので定数にしました！
